  List<String> characterList = [
    "Grant Gustin",
    "Candice Patton",
    "Danielle Panabaker",
    "Carlos Valdes",
    "Tom Cavanagh",
    "Jesse L. Martin",
    "Danielle Nicolet",
    "Hartley Sawyer",
    "Keiynan Lonsdale",
    "Jessica Parker Kennedy",
    "John Wesley Shipp",
    "Kayla Compton",
    "Patrick Sabongui",
    "Rick Cosnett",
    "Wentworth Miller",
    "Brandon McKnight",
    "Stephen Amell",
    "Emily Bett Rickards"
  ];